name: test
description: A short description of my Dart project.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  asn1lib: ^1.4.0
  crypto: ^3.0.3
  cryptography: ^2.5.0
  encrypt: ^5.0.1
  http: ^0.13.3
  path: ^1.8.0
  pointycastle: ^3.7.3

